version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-mono
    steps:
      - checkout
      # - run: npm i node-gyp -g
      - run: npm install -g cmake-js
      # - run: npm config set arch ia32
      - run: node -v
      - run: npm -v
      # - run: npm config list
      # - run: node-gyp -v
      - run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2.tar.gz
          tar xvf cmake-3.13.2.tar.gz
          cd cmake-3.13.2
          ./bootstrap && make && make install
      - run: cmake --version
      - run: npm install
      - run: ls -l .
      - run: ls -l node_modules
      - run: ./node_modules/.bin/electron-rebuild
      - run: npm run build
      - store_artifacts:
          path: dist
