version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-mono
    steps:
      - checkout
      - run: npm i node-gyp -g
      - run: npm config set arch win
      # - run: npm config set loglevel silly
      - run: node -v
      - run: npm -v
      - run: npm config list
      - run: node-gyp -v
      - run: mcs -v
      - run: npm i
      - run: ls -l .
      - run: ls -l node_modules
      - run: ./node_modules/.bin/electron-rebuild
      - run: npm run build
      - store_artifacts:
          path: dist
